# Generated by Django 3.0.8 on 2021-04-11 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0004_task_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
